id: P299D6BD9
initial_creation_type: input
source_metadata:
  title: Rago Choktrul Tupten Shedrup Gyatso
  language: en
  description: 'Texts by and about Rago Choktrul Tupten Shedrup Gyatso (rag mgo mchog
    sprul thub bstan bshad sgrub rgya mtsho, 1879–1972), a prolific author of the
    Palyul tradition:'
  volume:
    00e971a9445946df98c477c33ee42715:
      title: 'Vines of Amṛta: A Prayer to the Lineage of the Bodhicaryāvatāra'
      parent: Lineage Prayers
created_at: '2022-03-01T01:18:27.667764'
last_modified_at: '2022-03-01T01:18:27.667770'
